# Generated by Django 3.2.9 on 2021-11-28 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_price', 'Fixed Price'), ('fixed_amount', 'Fixed Amount'), ('fixed_number', 'Fixed Number')], default='percentage', max_length=15, verbose_name='Type')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('SEK', 'Krona')], default='USD', max_length=3, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Discount Type',
                'verbose_name_plural': 'Discount Types',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='End Date')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Discount Code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('active', 'Active')], default='active', max_length=7, verbose_name='Status')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.store')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.discounttype')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
    ]
