# Generated by Django 3.2.9 on 2021-11-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='type',
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Discount Code'),
        ),
    ]
